disease:
  alpha: 0.8  # The effectiveness of the receiver's intervention
  beta: 0.8  # The effectiveness of the spreader's intervention
  p_SI: 0.05  # The baseline transmission probability (S -> I)
  p_IH: 0.01  # The probability of hospitalization (I -> H)
  p_IR: 0.05  # The probability of recovery from infection (I -> R)
  p_HR: 0.10  # The probability of recovery from hospitalization (H -> R)
  p_RS: 0.03  # The probability of being susceptible from recovery (R -> S)

social:
  p_s: 0.20  # The probability of a versatile agents behaving stubborn

population:
  frac_stubborn: 0.3  # The fraction of stubborn agents
  frac_prosocial: 0.2  # The fraction of prosocial agents
  tau:  # The peer-effect threshold (tau_u)
    name: uniform
    low: 0.2
    high: 0.6
  gamma:  # The local fear threshold (gamma_u)
    name: uniform
    low: 0.1
    high: 0.3
  lam:  # The global fear threshold (lam_u)
    name: const
    value: 0.02

init: # Initial (day-0) fraction of: 
  init_infected_frac: 0.01  # Infections
  init_adopted_frac: 0.00  # Social contagion adoptions
  init_recovered_frac: 0.0  # Recovered agents
  init_hospitalized_frac: 0.0  # Hospitalized agents